name: unison-codebase
github: unisonweb/unison

dependencies:
  - base
  - containers
  - generic-lens
  - lens
  - mtl
  - text
  - time
  - unison-core
  - unison-hash
  - unison-prelude
  - unison-util-base32hex

library:
  source-dirs: .
  when:
    - condition: false
      other-modules: Paths_unison_codebase

default-extensions:
  - BlockArguments
  - DerivingStrategies
  - LambdaCase

language: GHC2021
